package das.losaparecidos.etzi.app.ui.theme
import androidx.compose.ui.graphics.Color


val md_theme_light_primary = Color(0xFF006c48)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFF8bf8c4)
val md_theme_light_onPrimaryContainer = Color(0xFF002113)
val md_theme_light_secondary = Color(0xFF4d6357)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFcfe8d8)
val md_theme_light_onSecondaryContainer = Color(0xFF0a1f16)
val md_theme_light_tertiary = Color(0xFF3d6473)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFc1e9fb)
val md_theme_light_onTertiaryContainer = Color(0xFF001f29)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfbfdf8)
val md_theme_light_onBackground = Color(0xFF191c1a)
val md_theme_light_surface = Color(0xFFfbfdf8)
val md_theme_light_onSurface = Color(0xFF191c1a)
val md_theme_light_surfaceVariant = Color(0xFFdce5dd)
val md_theme_light_onSurfaceVariant = Color(0xFF404943)
val md_theme_light_outline = Color(0xFF707973)
val md_theme_light_inverseOnSurface = Color(0xFFeff1ed)
val md_theme_light_inverseSurface = Color(0xFF2d312e)
val md_theme_light_inversePrimary = Color(0xFF6edba9)

val md_theme_dark_primary = Color(0xFF6edba9)
val md_theme_dark_onPrimary = Color(0xFF003823)
val md_theme_dark_primaryContainer = Color(0xFF005236)
val md_theme_dark_onPrimaryContainer = Color(0xFF8bf8c4)
val md_theme_dark_secondary = Color(0xFFb3ccbc)
val md_theme_dark_onSecondary = Color(0xFF1f352a)
val md_theme_dark_secondaryContainer = Color(0xFF364b40)
val md_theme_dark_onSecondaryContainer = Color(0xFFcfe8d8)
val md_theme_dark_tertiary = Color(0xFFa5cdde)
val md_theme_dark_onTertiary = Color(0xFF063543)
val md_theme_dark_tertiaryContainer = Color(0xFF244c5b)
val md_theme_dark_onTertiaryContainer = Color(0xFFc1e9fb)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF191c1a)
val md_theme_dark_onBackground = Color(0xFFe1e3df)
val md_theme_dark_surface = Color(0xFF191c1a)
val md_theme_dark_onSurface = Color(0xFFe1e3df)
val md_theme_dark_surfaceVariant = Color(0xFF404943)
val md_theme_dark_onSurfaceVariant = Color(0xFFbfc9c1)
val md_theme_dark_outline = Color(0xFF8a938c)
val md_theme_dark_inverseOnSurface = Color(0xFF191c1a)
val md_theme_dark_inverseSurface = Color(0xFFe1e3df)
val md_theme_dark_inversePrimary = Color(0xFF006c48)